x-backend-common: &backend-common
  build:
    context: ./backend
    dockerfile: Dockerfile.dev
  volumes:
    - ./backend:/backend
  depends_on:
    - db
  env_file:
    - ./backend/.local.env

services:
  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.local.env

  backend:
    <<: *backend-common
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  backend_cmd:
    <<: *backend-common
    command: sh -c "tail -f /dev/null"  # Keep the container running
    ports: [ ]  # Remove port binding to avoid conflicts

volumes:
  postgres_data:
