# Start from a Python base image
FROM python:3.12.4-slim-bullseye

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory in container
WORKDIR /backend

# Install dependencies
COPY requirements.txt requirements-dev.txt /backend/
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements-dev.txt

# Copy the rest of the application code
COPY . /backend/
